// Generated by CoffeeScript 1.10.0
(function() {
  var $, isRetina, load2x, win;

  win = window;

  $ = win.jQuery;

  isRetina = function() {
    var mediaQuery;
    if (win.devicePixelRatio > 1) {
      return true;
    }
    mediaQuery = '(-webkit-min-device-pixel-ratio: 2), (min--moz-device-pixel-ratio: 2), (-o-min-device-pixel-ratio: 2/1), (min-device-pixel-ratio: 2), (min-resolution: 192dpi), (min-resolution: 2dppx)';
    if (win.matchMedia && win.matchMedia(mediaQuery).matches) {
      return true;
    }
    return false;
  };

  load2x = function() {
    var regexMatch, suffix, suffixReplace;
    suffix = '-2x';
    regexMatch = /\.\w+$/;
    suffixReplace = function(str) {
      return suffix + str;
    };
    return $('img:not([data-no-retina])').each(function() {
      var $img, $tmpImg, parts, src2;
      $img = $(this);
      parts = $img.attr('src').split('?');
      parts[0] = parts[0].replace(regexMatch, suffixReplace);
      src2 = parts.join('?');
      $tmpImg = $('<img>');
      $tmpImg.on('load', function() {
        setTimeout(function() {
          var attr;
          attr = {
            'src': src2
          };
          if ($img.width()) {
            attr['width'];
          }
          if ($img.height()) {
            attr['height'];
          }
          $img.attr(attr);
        }, 10);
      });
      $tmpImg.attr('src', src2);
    });
  };

  if (isRetina()) {
    $(win).on('load', load2x);
  }

}).call(this);

//# sourceMappingURL=retina-2x.js.map
